# Generated by Django 4.2.30 on 2026-06-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('group', models.CharField(blank=True, max_length=10, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('ai_commentary', models.TextField(blank=True, null=True)),
                ('is_upset_alert', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fifa_rank', models.IntegerField(blank=True, null=True)),
                ('elo_rating', models.FloatField(default=1500.0)),
                ('recent_form', models.FloatField(default=5.0)),
                ('confederation', models.CharField(blank=True, max_length=50, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=20, null=True)),
                ('tactical_formation', models.CharField(blank=True, max_length=50, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('historical_performance', models.TextField(blank=True, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=150, null=True)),
                ('manager_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('foundation_year', models.IntegerField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('home_stadium', models.CharField(blank=True, max_length=200, null=True)),
                ('squad_market_value', models.FloatField(default=0.0)),
                ('world_cup_appearances', models.IntegerField(default=0)),
                ('best_wc_result', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('secondary_color', models.CharField(default='#000000', max_length=7)),
                ('ai_outlook', models.TextField(blank=True, null=True)),
                ('fan_support_count', models.BigIntegerField(default=0)),
                ('qualification_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fifa_rank'],
            },
        ),
        migrations.CreateModel(
            name='TournamentSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iterations', models.IntegerField()),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_prob', models.FloatField()),
                ('draw_prob', models.FloatField()),
                ('loss_prob', models.FloatField()),
                ('xg_home', models.FloatField()),
                ('xg_away', models.FloatField()),
                ('ai_confidence', models.FloatField()),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_predictions', to='api.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_predictions', to='api.team')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=50)),
                ('position_code', models.CharField(blank=True, max_length=5, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('preferred_foot', models.CharField(blank=True, max_length=10, null=True)),
                ('club', models.CharField(blank=True, max_length=150, null=True)),
                ('club_country', models.CharField(blank=True, max_length=100, null=True)),
                ('national_appearances', models.IntegerField(default=0)),
                ('market_value', models.FloatField(blank=True, null=True)),
                ('recent_form', models.FloatField(default=5.0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('injury_status', models.BooleanField(default=False)),
                ('injury_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('ai_rating', models.IntegerField(default=75)),
                ('heat_map_data', models.JSONField(blank=True, null=True)),
                ('seasonal_stats', models.JSONField(blank=True, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team')),
            ],
            options={
                'ordering': ['-ai_rating'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='api.team'),
        ),
        migrations.CreateModel(
            name='FanSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_supporters', models.BigIntegerField(default=0)),
                ('supporters_today', models.BigIntegerField(default=0)),
                ('supporters_this_week', models.BigIntegerField(default=0)),
                ('last_support_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fan_support', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWorldCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('host_nation', models.CharField(max_length=100)),
                ('stage_reached', models.CharField(max_length=100)),
                ('final_placement', models.IntegerField(blank=True, null=True)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('top_scorer', models.CharField(blank=True, max_length=150, null=True)),
                ('top_scorer_goals', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wc_history', to='api.team')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('team', 'year')},
            },
        ),
    ]
