"""
World Cup Oracle AI - V3 Comprehensive Seed Script
Seeds all 48 FIFA World Cup 2026 nations with realistic player data,
World Cup history, colors, and fan support stats.
"""
import os, sys, django, random, json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from api.models import Team, Player, HistoricalWorldCup, FanSupport

# ─── TEAM DATA ─────────────────────────────────────────────────────────────────

TEAMS = [
    # CONMEBOL
    {"name": "Argentina", "fifa_rank": 1, "elo": 2090, "form": 8.5, "confed": "CONMEBOL", "flag": "🇦🇷",
     "manager": "Lionel Scaloni", "manager_nat": "Argentine", "founded": 1893, "nickname": "La Albiceleste",
     "stadium": "Estadio Monumental", "squad_value": 820, "wc_apps": 18, "best": "Champions (2022)",
     "primary": "#74ACDF", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "World-class attacking talent, exceptional team chemistry, proven tournament winners, mental resilience",
     "weaknesses": "Over-reliance on Messi era, depth at centre-back, vulnerable to high press",
     "outlook": "Defending champions Argentina arrive as co-favourites. Messi's twilight years bring urgency, and this squad has the chemistry to go all the way again.",
     "qualification": "CONMEBOL qualifiers — 1st place, 22 points"},
    {"name": "Brazil", "fifa_rank": 5, "elo": 2145, "form": 8.2, "confed": "CONMEBOL", "flag": "🇧🇷",
     "manager": "Dorival Junior", "manager_nat": "Brazilian", "founded": 1914, "nickname": "A Seleção",
     "stadium": "Estádio do Maracanã", "squad_value": 980, "wc_apps": 22, "best": "Champions (2002)",
     "primary": "#009C3B", "secondary": "#FFDF00", "formation": "4-2-3-1",
     "strengths": "World's most valuable squad, incredible attacking depth, relentless pressing, technical excellence",
     "weaknesses": "Tournament pressure management, defensive frailties on set pieces",
     "outlook": "The most talented squad in the tournament. Vinicius Jr, Rodrygo, and Endrick form a devastating front three. The only question is their ability to handle the weight of expectation.",
     "qualification": "CONMEBOL qualifiers — 2nd place, 21 points"},
    {"name": "Colombia", "fifa_rank": 9, "elo": 1880, "form": 8.8, "confed": "CONMEBOL", "flag": "🇨🇴",
     "manager": "Néstor Lorenzo", "manager_nat": "Argentine", "founded": 1924, "nickname": "Los Cafeteros",
     "stadium": "Estadio El Campín", "squad_value": 420, "wc_apps": 7, "best": "Quarterfinals (2014)",
     "primary": "#FCD116", "secondary": "#003087", "formation": "4-2-3-1",
     "strengths": "Exceptional recent form, physical midfield, dangerous on the counter, James Rodriguez creativity",
     "weaknesses": "Inconsistency under pressure, limited World Cup pedigree at the highest level",
     "outlook": "Unbeaten in CONMEBOL qualifying. Colombia comes in as a dark horse with serious potential to reach the semifinals.",
     "qualification": "CONMEBOL qualifiers — 3rd place, 19 points"},
    {"name": "Uruguay", "fifa_rank": 16, "elo": 1840, "form": 7.5, "confed": "CONMEBOL", "flag": "🇺🇾",
     "manager": "Marcelo Bielsa", "manager_nat": "Argentine", "founded": 1900, "nickname": "La Celeste",
     "stadium": "Estadio Centenario", "squad_value": 260, "wc_apps": 14, "best": "Champions (1930, 1950)",
     "primary": "#5EB6E4", "secondary": "#FFFFFF", "formation": "4-4-2",
     "strengths": "Tactical discipline, clinical finishing, defensive organization, winning mentality",
     "weaknesses": "Aging squad, reliance on Valverde and Nunez, poor depth in attack",
     "outlook": "Bielsa's Uruguay play intensely structured football. With Darwin Nunez and Federico Valverde, they can beat anyone on their day.",
     "qualification": "CONMEBOL qualifiers — 4th place, 16 points"},
    {"name": "Ecuador", "fifa_rank": 24, "elo": 1700, "form": 6.8, "confed": "CONMEBOL", "flag": "🇪🇨",
     "manager": "Sebastián Beccacece", "manager_nat": "Argentine", "founded": 1925, "nickname": "La Tri",
     "stadium": "Estadio Rodrigo Paz", "squad_value": 160, "wc_apps": 4, "best": "Round of 16 (2006)",
     "primary": "#FFD100", "secondary": "#0072CE", "formation": "4-3-3",
     "strengths": "Physical and direct, strong home form, dangerous set pieces",
     "weaknesses": "Limited experience at the highest level, squad depth concerns",
     "outlook": "Ecuador's young squad is still developing. They'll aim to make the knockout stages but face steep competition in their group.",
     "qualification": "CONMEBOL qualifiers — 5th place"},
    {"name": "Paraguay", "fifa_rank": 58, "elo": 1620, "form": 6.2, "confed": "CONMEBOL", "flag": "🇵🇾",
     "manager": "Gustavo Alfaro", "manager_nat": "Argentine", "founded": 1906, "nickname": "La Albirroja",
     "stadium": "Estadio Defensores del Chaco", "squad_value": 95, "wc_apps": 9, "best": "Quarterfinals (2010)",
     "primary": "#D52B1E", "secondary": "#FFFFFF", "formation": "4-4-2",
     "strengths": "Fighting spirit, solid defense, set piece threat",
     "weaknesses": "Limited attacking quality, overly defensive approach, lack of global star power",
     "outlook": "Paraguay qualify via the expanded format and will look to be organized and difficult to beat. Causing an upset is not out of the question.",
     "qualification": "CONMEBOL playoff — 6th place"},
    # CONCACAF
    {"name": "USA", "fifa_rank": 11, "elo": 1880, "form": 7.4, "confed": "CONCACAF", "flag": "🇺🇸",
     "manager": "Mauricio Pochettino", "manager_nat": "Argentine", "founded": 1913, "nickname": "The Stars and Stripes",
     "stadium": "MetLife Stadium", "squad_value": 380, "wc_apps": 11, "best": "Quarterfinals (2002)",
     "primary": "#002868", "secondary": "#BF0A30", "formation": "4-3-3",
     "strengths": "Athletic intensity, Premier League-based core, Pulisic quality, home advantage as co-hosts",
     "weaknesses": "Inconsistency against top-level opposition, lacks a world-class striker",
     "outlook": "As co-hosts, the USA carry massive expectations. Pulisic, McKennie, and Reyna form a gifted midfield. Under Pochettino, they have genuine knockout potential.",
     "qualification": "CONCACAF automatic — co-hosts"},
    {"name": "Mexico", "fifa_rank": 14, "elo": 1850, "form": 6.8, "confed": "CONCACAF", "flag": "🇲🇽",
     "manager": "Javier Aguirre", "manager_nat": "Mexican", "founded": 1927, "nickname": "El Tri",
     "stadium": "Estadio Azteca", "squad_value": 180, "wc_apps": 17, "best": "Quarterfinals (1970, 1986)",
     "primary": "#006847", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Tournament experience, aggressive pressing, passionate support, familiar conditions as co-host",
     "weaknesses": "Curse of the 5th game (never reached QF in modern era), lacks elite quality in attack",
     "outlook": "El Tri desperately want to break their Round of 16 curse. Co-hosting adds pressure but also energy. Hirving Lozano leads a talented but inconsistent squad.",
     "qualification": "CONCACAF automatic — co-hosts"},
    {"name": "Canada", "fifa_rank": 40, "elo": 1720, "form": 7.2, "confed": "CONCACAF", "flag": "🇨🇦",
     "manager": "Jesse Marsch", "manager_nat": "American", "founded": 1912, "nickname": "The Canucks",
     "stadium": "BMO Field", "squad_value": 200, "wc_apps": 2, "best": "Group Stage (2022)",
     "primary": "#FF0000", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Young, athletic, fearless; Alphonso Davies pace and quality; physical pressing style",
     "weaknesses": "Limited WC experience, inconsistent goal-scoring, fragile under pressure",
     "outlook": "Canada's golden generation is arriving. Davies, Buchanan, and Johnston give them genuine quality. Their 2026 will be a statement tournament.",
     "qualification": "CONCACAF automatic — co-hosts"},
    {"name": "Panama", "fifa_rank": 72, "elo": 1560, "form": 6.5, "confed": "CONCACAF", "flag": "🇵🇦",
     "manager": "Thomas Christiansen", "manager_nat": "Danish", "founded": 1937, "nickname": "Los Canaleros",
     "stadium": "Estadio Rommel Fernández", "squad_value": 40, "wc_apps": 2, "best": "Group Stage (2018)",
     "primary": "#DA121A", "secondary": "#FFFFFF", "formation": "4-4-2",
     "strengths": "Defensive solidity, physical approach, set pieces",
     "weaknesses": "Limited creative quality, exposed against elite pace and skill",
     "outlook": "Panama's third World Cup appearance. They'll be organized and difficult to break down but unlikely to progress beyond the group stage.",
     "qualification": "CONCACAF 4th place"},
    {"name": "Haiti", "fifa_rank": 98, "elo": 1480, "form": 5.8, "confed": "CONCACAF", "flag": "🇭🇹",
     "manager": "Marc Collat", "manager_nat": "French", "founded": 1904, "nickname": "Les Grenadiers",
     "stadium": "Sylvio Cator Stadium", "squad_value": 15, "wc_apps": 1, "best": "Group Stage (1974)",
     "primary": "#00209F", "secondary": "#D21034", "formation": "4-4-2",
     "strengths": "Spirit and determination, underdog mentality, physical resilience",
     "weaknesses": "Significant quality gap versus most opponents, limited professional infrastructure",
     "outlook": "Haiti's appearance is a historic achievement. Expect spirited performances even if results are difficult.",
     "qualification": "CONCACAF playoff"},
    {"name": "Curacao", "fifa_rank": 82, "elo": 1510, "form": 6.0, "confed": "CONCACAF", "flag": "🇨🇼",
     "manager": "Remko Bicentini", "manager_nat": "Dutch", "founded": 1921, "nickname": "The Strikers",
     "stadium": "Ergilio Hato Stadium", "squad_value": 25, "wc_apps": 0, "best": "First appearance",
     "primary": "#002B7F", "secondary": "#F9E814", "formation": "4-3-3",
     "strengths": "Dutch-influenced technical football, flair in attack, motivated squad",
     "weaknesses": "First World Cup appearance, inexperienced at this level",
     "outlook": "A historic debut for Curacao. They'll play free, expressive football and will look to announce themselves on the world stage.",
     "qualification": "CONCACAF 5th place"},
    # UEFA
    {"name": "France", "fifa_rank": 2, "elo": 2110, "form": 8.8, "confed": "UEFA", "flag": "🇫🇷",
     "manager": "Didier Deschamps", "manager_nat": "French", "founded": 1919, "nickname": "Les Bleus",
     "stadium": "Stade de France", "squad_value": 1100, "wc_apps": 16, "best": "Champions (1998, 2018)",
     "primary": "#002395", "secondary": "#ED2939", "formation": "4-2-3-1",
     "strengths": "Most expensive squad in the tournament, devastating on the counter, Mbappe's world-class quality, depth across all positions",
     "weaknesses": "Historically underperform expectations, dressing room tensions",
     "outlook": "France are arguably the strongest squad on paper. Two-time champions with Mbappe in his prime — they must be considered the outright favourites.",
     "qualification": "UEFA — Group B winners"},
    {"name": "England", "fifa_rank": 4, "elo": 2050, "form": 7.8, "confed": "UEFA", "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
     "manager": "Thomas Tuchel", "manager_nat": "German", "founded": 1863, "nickname": "The Three Lions",
     "stadium": "Wembley Stadium", "squad_value": 860, "wc_apps": 16, "best": "Champions (1966)",
     "primary": "#FFFFFF", "secondary": "#CF081F", "formation": "4-2-3-1",
     "strengths": "Bellingham's elite midfield quality, Kane's clinical finishing, Premier League core, strong squad depth",
     "weaknesses": "Penalty heartbreak history, tendency to underperform at major tournaments",
     "outlook": "Under Tuchel's tactically demanding approach, England have a real chance. Bellingham and Kane are a world-class axis. 60 years of hurt could finally end.",
     "qualification": "UEFA — Group C winners"},
    {"name": "Spain", "fifa_rank": 7, "elo": 2020, "form": 8.5, "confed": "UEFA", "flag": "🇪🇸",
     "manager": "Luis de la Fuente", "manager_nat": "Spanish", "founded": 1909, "nickname": "La Roja",
     "stadium": "Estadio Santiago Bernabéu", "squad_value": 780, "wc_apps": 16, "best": "Champions (2010)",
     "primary": "#AA151B", "secondary": "#F1BF00", "formation": "4-3-3",
     "strengths": "Lamine Yamal's generational talent, technical superiority, high press, possession domination",
     "weaknesses": "Reliance on young players in high-pressure moments, sometimes lack cutting edge",
     "outlook": "Euro 2024 winners arrive with incredible momentum. Spain's beautiful football and Lamine Yamal's magic make them one of the most exciting teams in the competition.",
     "qualification": "UEFA — Group A winners"},
    {"name": "Germany", "fifa_rank": 13, "elo": 1980, "form": 7.5, "confed": "UEFA", "flag": "🇩🇪",
     "manager": "Julian Nagelsmann", "manager_nat": "German", "founded": 1900, "nickname": "Die Mannschaft",
     "stadium": "Allianz Arena", "squad_value": 620, "wc_apps": 20, "best": "Champions (1954, 1974, 1990, 2014)",
     "primary": "#000000", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Tactical flexibility, tournament experience, Musiala and Havertz quality, clinical counter-attacks",
     "weaknesses": "Inconsistency after 2014 peak, occasionally rigid tactical approach",
     "outlook": "Four-time champions rebuilding under Nagelsmann. Musiala and Havertz form a formidable partnership. Germany will want to reclaim their place among the elite.",
     "qualification": "UEFA — Group E winners"},
    {"name": "Portugal", "fifa_rank": 6, "elo": 1960, "form": 8.3, "confed": "UEFA", "flag": "🇵🇹",
     "manager": "Roberto Martínez", "manager_nat": "Spanish", "founded": 1914, "nickname": "A Seleção das Quinas",
     "stadium": "Estádio da Luz", "squad_value": 750, "wc_apps": 9, "best": "3rd Place (1966)",
     "primary": "#006600", "secondary": "#FF0000", "formation": "4-3-3",
     "strengths": "Bruno Fernandes creativity, Ronaldo's experience, physical intensity, strong defensive block",
     "weaknesses": "Too dependent on aging Ronaldo, lacks consistently elite striker beyond him",
     "outlook": "Portugal's post-Ronaldo era is arriving. Martinez has transformed them into a collectivist, high-energy side with genuine dark horse potential.",
     "qualification": "UEFA — Group F winners"},
    {"name": "Netherlands", "fifa_rank": 8, "elo": 1950, "form": 7.2, "confed": "UEFA", "flag": "🇳🇱",
     "manager": "Ronald Koeman", "manager_nat": "Dutch", "founded": 1889, "nickname": "Oranje",
     "stadium": "Johan Cruyff Arena", "squad_value": 510, "wc_apps": 11, "best": "Runners-up (1974, 1978, 2010)",
     "primary": "#FF6200", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Van Dijk's defensive leadership, Gakpo's technical quality, disciplined defensive shape",
     "weaknesses": "Inconsistent away from home, can lack creativity when compact sides defend deep",
     "outlook": "The Dutch are a dangerous knockout-round opponent. Never count out Oranje at a World Cup — they have a knack for tournament football.",
     "qualification": "UEFA — Group G winners"},
    {"name": "Belgium", "fifa_rank": 3, "elo": 1940, "form": 7.0, "confed": "UEFA", "flag": "🇧🇪",
     "manager": "Domenico Tedesco", "manager_nat": "Italian", "founded": 1895, "nickname": "The Red Devils",
     "stadium": "King Baudouin Stadium", "squad_value": 420, "wc_apps": 14, "best": "3rd Place (1986, 2018)",
     "primary": "#000000", "secondary": "#ED1C24", "formation": "3-4-3",
     "strengths": "De Bruyne's elite vision, Lukaku's experience, Courtois goalkeeping, technical class",
     "weaknesses": "Golden generation potentially past peak, De Bruyne's fitness crucial",
     "outlook": "Belgium's last golden generation tournament? De Bruyne is world-class and this could be his crowning achievement. Expect them to reach at least the quarterfinals.",
     "qualification": "UEFA — Group H winners"},
    {"name": "Croatia", "fifa_rank": 10, "elo": 1910, "form": 6.5, "confed": "UEFA", "flag": "🇭🇷",
     "manager": "Zlatko Dalic", "manager_nat": "Croatian", "founded": 1912, "nickname": "Vatreni",
     "stadium": "Stadion Poljud", "squad_value": 230, "wc_apps": 7, "best": "Runners-up (2018)",
     "primary": "#FF0000", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Modric's leadership, midfield experience, never-say-die mentality, excellent team cohesion",
     "weaknesses": "Aging squad, less explosive than 2018 vintage, lack of quality finisher",
     "outlook": "Modric's final World Cup. Croatia are masters of tournament football and regularly exceed expectations. Another deep run is entirely possible.",
     "qualification": "UEFA — Group I winners"},
    {"name": "Italy", "fifa_rank": 9, "elo": 1930, "form": 7.3, "confed": "UEFA", "flag": "🇮🇹",
     "manager": "Luciano Spalletti", "manager_nat": "Italian", "founded": 1898, "nickname": "Gli Azzurri",
     "stadium": "Stadio Olimpico", "squad_value": 460, "wc_apps": 18, "best": "Champions (1934, 1938, 1982, 2006)",
     "primary": "#003399", "secondary": "#FFFFFF", "formation": "3-4-3",
     "strengths": "Tactical sophistication, Serie A-based defensive excellence, Donnarumma quality, tournament experience",
     "weaknesses": "Attacking creativity can be limited, memories of 2018 and 2022 qualifying failures",
     "outlook": "Italy are back, determined to show their 2018 and 2022 absences were blips. Spalletti's system is ambitious and Donnarumma is world-class.",
     "qualification": "UEFA — Group B runners-up"},
    {"name": "Switzerland", "fifa_rank": 21, "elo": 1810, "form": 6.8, "confed": "UEFA", "flag": "🇨🇭",
     "manager": "Murat Yakin", "manager_nat": "Swiss", "founded": 1895, "nickname": "La Nati",
     "stadium": "Stade de Genève", "squad_value": 220, "wc_apps": 12, "best": "Quarterfinals (1934, 1938, 1954)",
     "primary": "#FF0000", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Defensively compact, regularly causes upsets, reliable performances against big nations",
     "weaknesses": "Lack of explosive attacking talent, often exits on penalties",
     "outlook": "Switzerland always over-achieve at World Cups. Xhaka's leadership and their defensive organization make them a nightmare to face.",
     "qualification": "UEFA — Group C runners-up"},
    {"name": "Austria", "fifa_rank": 25, "elo": 1760, "form": 7.0, "confed": "UEFA", "flag": "🇦🇹",
     "manager": "Ralf Rangnick", "manager_nat": "German", "founded": 1904, "nickname": "Das Team",
     "stadium": "Ernst Happel Stadion", "squad_value": 290, "wc_apps": 7, "best": "3rd Place (1954)",
     "primary": "#ED2939", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "High-intensity pressing under Rangnick, technically gifted midfield, strong Bundesliga core",
     "weaknesses": "Limited World Cup experience in modern era, can be vulnerable on the counter",
     "outlook": "Austria under Rangnick play breathtaking attacking football. They're a genuine dark horse with the potential to surprise several heavyweights.",
     "qualification": "UEFA — Group D winners"},
    {"name": "Denmark", "fifa_rank": 22, "elo": 1810, "form": 6.5, "confed": "UEFA", "flag": "🇩🇰",
     "manager": "Brian Riemer", "manager_nat": "Danish", "founded": 1889, "nickname": "Danish Dynamite",
     "stadium": "Parken Stadium", "squad_value": 310, "wc_apps": 6, "best": "Quarterfinals (1998)",
     "primary": "#C60C30", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Eriksen's creativity, collective spirit, strong defensive base, reliable",
     "weaknesses": "Struggles to unlock compact defenses, relies heavily on Eriksen",
     "outlook": "Denmark are always dangerous. Eriksen's comeback story adds extra motivation to a team that punches above their weight consistently.",
     "qualification": "UEFA — Group E runners-up"},
    {"name": "Serbia", "fifa_rank": 30, "elo": 1720, "form": 6.3, "confed": "UEFA", "flag": "🇷🇸",
     "manager": "Dragan Stojković", "manager_nat": "Serbian", "founded": 1919, "nickname": "Orlovi",
     "stadium": "Rajko Mitić Stadium", "squad_value": 230, "wc_apps": 13, "best": "4th Place (1930)",
     "primary": "#C6363C", "secondary": "#0C4076", "formation": "4-2-3-1",
     "strengths": "Mitrovic's physicality, talented midfield, passionate players, tactical discipline",
     "weaknesses": "Inconsistent team chemistry, can be tactically rigid",
     "outlook": "Serbia possess real quality with Mitrovic and Vlahovic leading the attack. They're capable of a knockout run but need consistency.",
     "qualification": "UEFA — Group G runners-up"},
    {"name": "Turkey", "fifa_rank": 28, "elo": 1740, "form": 7.0, "confed": "UEFA", "flag": "🇹🇷",
     "manager": "Vincenzo Montella", "manager_nat": "Italian", "founded": 1923, "nickname": "Ay-Yıldızlılar",
     "stadium": "Türk Telekom Stadium", "squad_value": 280, "wc_apps": 2, "best": "3rd Place (2002)",
     "primary": "#E30A17", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Arda Guler's exceptional talent, physical intensity, passionate performances, improving quality",
     "weaknesses": "Inconsistent finishing, limited World Cup experience",
     "outlook": "Turkey's best generation in 20 years. Arda Guler's Madrid form gives them an X-factor. A surprise run to the quarterfinals is entirely possible.",
     "qualification": "UEFA — Group F runners-up"},
    {"name": "Norway", "fifa_rank": 35, "elo": 1700, "form": 7.2, "confed": "UEFA", "flag": "🇳🇴",
     "manager": "Ståle Solbakken", "manager_nat": "Norwegian", "founded": 1902, "nickname": "Løvene",
     "stadium": "Ullevaal Stadion", "squad_value": 210, "wc_apps": 4, "best": "Second Round (1994, 1998)",
     "primary": "#EF2B2D", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Haaland's world-class goals, direct attacking play, physical presence",
     "weaknesses": "Team quality significantly drops without Haaland, defensive vulnerabilities",
     "outlook": "Norway are Haaland's team. If he stays fit and in form, they can genuinely challenge. A Haaland World Cup is one of the most anticipated events in football.",
     "qualification": "UEFA — Group A runners-up"},
    {"name": "Scotland", "fifa_rank": 39, "elo": 1680, "form": 6.4, "confed": "UEFA", "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
     "manager": "Steve Clarke", "manager_nat": "Scottish", "founded": 1873, "nickname": "The Tartan Army",
     "stadium": "Hampden Park", "squad_value": 110, "wc_apps": 8, "best": "Group Stage",
     "primary": "#005EB8", "secondary": "#FFFFFF", "formation": "3-5-2",
     "strengths": "Hard-working, disciplined defense, passionate players, difficult to beat",
     "weaknesses": "Limited quality at the top level, struggle to create chances against compact defenses",
     "outlook": "Scotland's first World Cup since 1998 is a massive achievement. They'll battle hard and make every game difficult. Progression would be a miracle.",
     "qualification": "UEFA — playoff winners"},
    {"name": "Sweden", "fifa_rank": 23, "elo": 1750, "form": 6.2, "confed": "UEFA", "flag": "🇸🇪",
     "manager": "Jon Dahl Tomasson", "manager_nat": "Danish", "founded": 1904, "nickname": "Blågult",
     "stadium": "Friends Arena", "squad_value": 130, "wc_apps": 12, "best": "3rd Place (1994)",
     "primary": "#006AA7", "secondary": "#FECC02", "formation": "4-4-2",
     "strengths": "Well-organized, technically solid, experienced squad, Forsberg creativity",
     "weaknesses": "Lacks a genuine world-class player, sometimes overly cautious",
     "outlook": "Sweden are reliable and well-organized. They'll be tough to beat but will need a special performance to make the semifinals.",
     "qualification": "UEFA — playoff winners"},
    {"name": "Czech Republic", "fifa_rank": 33, "elo": 1660, "form": 6.0, "confed": "UEFA", "flag": "🇨🇿",
     "manager": "Ivan Hašek", "manager_nat": "Czech", "founded": 1901, "nickname": "Lvíčata",
     "stadium": "Doosan Arena", "squad_value": 100, "wc_apps": 10, "best": "Runners-up (1934, 1962)",
     "primary": "#D7141A", "secondary": "#11457E", "formation": "4-2-3-1",
     "strengths": "Organized defense, Schick's aerial quality, experienced players",
     "weaknesses": "Limited attacking options beyond Schick, aging squad",
     "outlook": "Czech Republic will be well-organized and difficult to beat. A group stage exit is likely but they'll make opponents work hard.",
     "qualification": "UEFA — playoff winners"},
    {"name": "Bosnia and Herzegovina", "fifa_rank": 47, "elo": 1640, "form": 6.5, "confed": "UEFA", "flag": "🇧🇦",
     "manager": "Sergej Barbarez", "manager_nat": "German", "founded": 1992, "nickname": "Zmajevi",
     "stadium": "Stadion Grbavica", "squad_value": 75, "wc_apps": 1, "best": "Group Stage (2014)",
     "primary": "#002395", "secondary": "#FCDD09", "formation": "4-3-3",
     "strengths": "Talented attack, direct playing style, dangerous on set pieces",
     "weaknesses": "Limited World Cup experience, inconsistent squad performances",
     "outlook": "Bosnia's second World Cup. They have exciting players but consistency at this level remains a challenge.",
     "qualification": "UEFA — playoff winners"},
    # CAF
    {"name": "Morocco", "fifa_rank": 12, "elo": 1860, "form": 8.0, "confed": "CAF", "flag": "🇲🇦",
     "manager": "Walid Regragui", "manager_nat": "Moroccan", "founded": 1955, "nickname": "Atlas Lions",
     "stadium": "Grand Stade Hassan II", "squad_value": 350, "wc_apps": 7, "best": "4th Place (2022)",
     "primary": "#C1272D", "secondary": "#006233", "formation": "4-3-3",
     "strengths": "Best African team in history, incredible defensive solidity, passionate home support, proven against elite teams",
     "weaknesses": "Limited African tournament wins, pressure of being continental favorites",
     "outlook": "Morocco's 2022 4th-place finish changed African football forever. Regragui's side are a genuine quarterfinal+ contender with the quality and mentality to go deep.",
     "qualification": "CAF — 1st place"},
    {"name": "Senegal", "fifa_rank": 19, "elo": 1800, "form": 7.2, "confed": "CAF", "flag": "🇸🇳",
     "manager": "Aliou Cissé", "manager_nat": "Senegalese", "founded": 1960, "nickname": "Lions of Teranga",
     "stadium": "Stade Léopold Sédar Senghor", "squad_value": 240, "wc_apps": 4, "best": "4th Place (2002)",
     "primary": "#00853F", "secondary": "#FDEF42", "formation": "4-3-3",
     "strengths": "Physical intensity, Diallo and Sarr quality, defensive organization, Cissé's experience",
     "weaknesses": "Mané's injury history crucial, inconsistent finishing",
     "outlook": "Senegal's talented squad can match any African nation. With Mané fit, they're capable of repeating their 2002 heroics.",
     "qualification": "CAF — 2nd place"},
    {"name": "Egypt", "fifa_rank": 31, "elo": 1740, "form": 6.8, "confed": "CAF", "flag": "🇪🇬",
     "manager": "Hossam Hassan", "manager_nat": "Egyptian", "founded": 1921, "nickname": "The Pharaohs",
     "stadium": "Cairo International Stadium", "squad_value": 120, "wc_apps": 3, "best": "Group Stage",
     "primary": "#CE1126", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Salah's world-class quality, passionate fan base, experienced defense",
     "weaknesses": "Over-dependent on Salah, squad depth drops off sharply",
     "outlook": "Egypt are Salah's team. At 34, this is likely his last World Cup chance. If fit and motivated, Salah could carry them to the Round of 16.",
     "qualification": "CAF — 3rd place"},
    {"name": "Algeria", "fifa_rank": 37, "elo": 1700, "form": 6.5, "confed": "CAF", "flag": "🇩🇿",
     "manager": "Vladimir Petkovic", "manager_nat": "Swiss", "founded": 1962, "nickname": "Les Fennecs",
     "stadium": "Stade Mustapha Tchaker", "squad_value": 95, "wc_apps": 4, "best": "Second Round (1982, 2014)",
     "primary": "#006233", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Mahrez-inspired attack, technical quality, dangerous on counter",
     "weaknesses": "Defense can be exposed, Mahrez approaching end of career",
     "outlook": "Algeria have quality but need Mahrez at his best. They'll aim to reach the knockout stages and create a moment of magic.",
     "qualification": "CAF — 4th place"},
    {"name": "Ghana", "fifa_rank": 60, "elo": 1620, "form": 6.0, "confed": "CAF", "flag": "🇬🇭",
     "manager": "Otto Addo", "manager_nat": "Ghanaian", "founded": 1957, "nickname": "Black Stars",
     "stadium": "Baba Yara Stadium", "squad_value": 80, "wc_apps": 4, "best": "Quarterfinals (2010)",
     "primary": "#006B3F", "secondary": "#FCD116", "formation": "4-3-3",
     "strengths": "Athletic ability, young talented squad, pacey wingers, passionate players",
     "weaknesses": "Defensive vulnerabilities, inconsistent performances",
     "outlook": "Ghana's Black Stars have potential but consistency remains an issue. A repeat of 2010 would be an incredible achievement.",
     "qualification": "CAF — 5th place"},
    {"name": "Tunisia", "fifa_rank": 29, "elo": 1700, "form": 6.2, "confed": "CAF", "flag": "🇹🇳",
     "manager": "Jalel Kadri", "manager_nat": "Tunisian", "founded": 1956, "nickname": "Eagles of Carthage",
     "stadium": "Stade Olympique de Radès", "squad_value": 65, "wc_apps": 6, "best": "Group Stage",
     "primary": "#E70013", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Defensive organization, experienced squad, technically competent",
     "weaknesses": "Limited attacking threat, rarely progress beyond groups",
     "outlook": "Tunisia are perennial World Cup participants who consistently fall short. They'll be organized but need a special tournament to advance.",
     "qualification": "CAF — 6th place"},
    {"name": "Ivory Coast", "fifa_rank": 53, "elo": 1640, "form": 6.8, "confed": "CAF", "flag": "🇨🇮",
     "manager": "Emerse Faé", "manager_nat": "Ivorian", "founded": 1960, "nickname": "Les Éléphants",
     "stadium": "Stade Félix Houphouët-Boigny", "squad_value": 140, "wc_apps": 3, "best": "Group Stage",
     "primary": "#F77F00", "secondary": "#009A44", "formation": "4-3-3",
     "strengths": "Athletic talent, Haller and Zaha quality, physical intensity",
     "weaknesses": "Inconsistent performances, struggle to translate talent into results",
     "outlook": "AFCON 2024 champions arrive with confidence. Ivory Coast have the quality but need consistency at the highest level.",
     "qualification": "CAF — 7th place"},
    {"name": "South Africa", "fifa_rank": 65, "elo": 1570, "form": 5.8, "confed": "CAF", "flag": "🇿🇦",
     "manager": "Hugo Broos", "manager_nat": "Belgian", "founded": 1991, "nickname": "Bafana Bafana",
     "stadium": "Soccer City", "squad_value": 40, "wc_apps": 3, "best": "Group Stage",
     "primary": "#007A4D", "secondary": "#FFB612", "formation": "4-4-2",
     "strengths": "Home continent advantage, physical resilience, passionate support",
     "weaknesses": "Limited international quality, sporadic performances",
     "outlook": "South Africa's return to the World Cup stage is celebrated. They'll face stiff competition but Bafana Bafana will make their continent proud.",
     "qualification": "CAF — 8th place"},
    {"name": "DR Congo", "fifa_rank": 77, "elo": 1540, "form": 6.0, "confed": "CAF", "flag": "🇨🇩",
     "manager": "Sébastien Desabre", "manager_nat": "French", "founded": 1919, "nickname": "Léopards",
     "stadium": "Stade des Martyrs", "squad_value": 50, "wc_apps": 2, "best": "Second Round (1974)",
     "primary": "#007FFF", "secondary": "#F7D618", "formation": "4-3-3",
     "strengths": "Explosive pace, technical skill in attack, improving infrastructure",
     "weaknesses": "Inconsistent results, limited major tournament experience",
     "outlook": "A historic qualification. DR Congo bring exciting players and unpredictable football — classic African wildcard potential.",
     "qualification": "CAF — 9th place"},
    {"name": "Cape Verde", "fifa_rank": 84, "elo": 1510, "form": 6.3, "confed": "CAF", "flag": "🇨🇻",
     "manager": "Pedro Brito", "manager_nat": "Cape Verdean", "founded": 1982, "nickname": "Tubarões Azuis",
     "stadium": "Estádio Nacional", "squad_value": 30, "wc_apps": 0, "best": "First appearance",
     "primary": "#003893", "secondary": "#CF2027", "formation": "4-4-2",
     "strengths": "Surprise factor, no pressure, plays with freedom, athletic and direct",
     "weaknesses": "Least experienced squad in tournament, massive step up in quality",
     "outlook": "Cape Verde's historic first World Cup. Every point will be celebrated. They'll play fearlessly with nothing to lose.",
     "qualification": "CAF playoff"},
    # AFC
    {"name": "Japan", "fifa_rank": 15, "elo": 1830, "form": 8.2, "confed": "AFC", "flag": "🇯🇵",
     "manager": "Hajime Moriyasu", "manager_nat": "Japanese", "founded": 1921, "nickname": "Samurai Blue",
     "stadium": "Japan National Stadium", "squad_value": 290, "wc_apps": 7, "best": "Round of 16",
     "primary": "#003F8A", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Excellent team organization, high pressing, European-based talent, Mitoma's pace and skill",
     "weaknesses": "Physical vulnerability against stronger nations, pressure from high expectations",
     "outlook": "Japan's European-based generation is the best in history. Mitoma, Kamada, and Endo make them Asia's strongest contender. A quarterfinal run is possible.",
     "qualification": "AFC — 1st place"},
    {"name": "South Korea", "fifa_rank": 20, "elo": 1760, "form": 7.0, "confed": "AFC", "flag": "🇰🇷",
     "manager": "Hong Myung-bo", "manager_nat": "South Korean", "founded": 1928, "nickname": "Taeguk Warriors",
     "stadium": "Seoul World Cup Stadium", "squad_value": 160, "wc_apps": 11, "best": "4th Place (2002)",
     "primary": "#CD2E3A", "secondary": "#003478", "formation": "4-3-3",
     "strengths": "Son Heung-min's world-class quality, physical intensity, tactical flexibility",
     "weaknesses": "Too reliant on Son, drops off dramatically in his absence",
     "outlook": "South Korea are Son Heung-min's team. If he stays fit, they're capable of producing magic. A second miracle run like 2002 would complete an incredible career.",
     "qualification": "AFC — 2nd place"},
    {"name": "Iran", "fifa_rank": 26, "elo": 1730, "form": 6.8, "confed": "AFC", "flag": "🇮🇷",
     "manager": "Amir Ghalenoei", "manager_nat": "Iranian", "founded": 1945, "nickname": "Team Melli",
     "stadium": "Azadi Stadium", "squad_value": 65, "wc_apps": 6, "best": "Group Stage",
     "primary": "#239F40", "secondary": "#FFFFFF", "formation": "4-4-2",
     "strengths": "Strong defensive organization, Taremi's quality, experienced in Asian football",
     "weaknesses": "Attacking creativity limited, inconsistent against European sides",
     "outlook": "Iran always qualify and always frustrate opponents. Taremi gives them a genuine goal threat. They'll aim to be competitive in every game.",
     "qualification": "AFC — 3rd place"},
    {"name": "Saudi Arabia", "fifa_rank": 42, "elo": 1640, "form": 6.8, "confed": "AFC", "flag": "🇸🇦",
     "manager": "Roberto Mancini", "manager_nat": "Italian", "founded": 1959, "nickname": "Green Falcons",
     "stadium": "King Fahd International Stadium", "squad_value": 55, "wc_apps": 6, "best": "Round of 16 (1994)",
     "primary": "#006C35", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Memorable 2022 Argentina win in the DNA, Mancini's organization, set pieces",
     "weaknesses": "Domestic league quality lower than top nations",
     "outlook": "Saudi Arabia shocked the world in 2022. Under Mancini, they'll try to be more consistent than just one legendary result.",
     "qualification": "AFC — 4th place"},
    {"name": "Australia", "fifa_rank": 23, "elo": 1720, "form": 6.5, "confed": "AFC", "flag": "🇦🇺",
     "manager": "Tony Popovic", "manager_nat": "Australian", "founded": 1961, "nickname": "Socceroos",
     "stadium": "Stadium Australia", "squad_value": 120, "wc_apps": 6, "best": "Quarterfinals (2006)",
     "primary": "#FFCD00", "secondary": "#00843D", "formation": "4-3-3",
     "strengths": "Leckie's pace, European-based players, physical approach, never give up mentality",
     "weaknesses": "Limited creative quality, long-haul travel impacts preparation",
     "outlook": "Australia's Socceroos are always dangerous outsiders. A repeat of their 2006 quarterfinal run would be celebrated across the nation.",
     "qualification": "AFC — 5th place"},
    {"name": "Japan", "fifa_rank": 15, "elo": 1830, "form": 8.2, "confed": "AFC", "flag": "🇯🇵",
     "manager": "Hajime Moriyasu", "manager_nat": "Japanese", "founded": 1921, "nickname": "Samurai Blue",
     "stadium": "Japan National Stadium", "squad_value": 290, "wc_apps": 7, "best": "Round of 16",
     "primary": "#003F8A", "secondary": "#FFFFFF", "formation": "4-2-3-1",
     "strengths": "Excellent team organization, high pressing, European-based talent",
     "weaknesses": "Physical vulnerability against stronger nations",
     "outlook": "Japan's European-based generation is the best in history.",
     "qualification": "AFC — 1st place"},
    {"name": "Iraq", "fifa_rank": 64, "elo": 1580, "form": 6.4, "confed": "AFC", "flag": "🇮🇶",
     "manager": "Jesus Casas", "manager_nat": "Spanish", "founded": 1948, "nickname": "Lions of Mesopotamia",
     "stadium": "Al-Shaab Stadium", "squad_value": 25, "wc_apps": 1, "best": "Group Stage (1986)",
     "primary": "#000000", "secondary": "#CE1126", "formation": "4-4-2",
     "strengths": "Improving quality, passionate players, direct approach",
     "weaknesses": "Significant quality gap versus top 10 nations",
     "outlook": "Iraq's second World Cup. They'll be competitive in Asian-level games but face immense challenges against the top sides.",
     "qualification": "AFC — 6th place"},
    {"name": "Qatar", "fifa_rank": 53, "elo": 1600, "form": 6.5, "confed": "AFC", "flag": "🇶🇦",
     "manager": "Márquez López", "manager_nat": "Spanish", "founded": 1960, "nickname": "Al Annabi",
     "stadium": "Lusail Iconic Stadium", "squad_value": 30, "wc_apps": 1, "best": "Group Stage (2022)",
     "primary": "#8D1B3D", "secondary": "#FFFFFF", "formation": "4-3-3",
     "strengths": "Heavily invested infrastructure, improving domestic league quality",
     "weaknesses": "Limited international quality, 2022 hosts showed the gap to world football",
     "outlook": "Qatar's qualification is hard-earned this time. They'll aim to show real improvement from their 2022 host appearance.",
     "qualification": "AFC — 7th place"},
    {"name": "Jordan", "fifa_rank": 70, "elo": 1540, "form": 6.2, "confed": "AFC", "flag": "🇯🇴",
     "manager": "Hussain Ammouta", "manager_nat": "Moroccan", "founded": 1949, "nickname": "Al-Nashama",
     "stadium": "King Abdullah II Stadium", "squad_value": 15, "wc_apps": 0, "best": "First appearance",
     "primary": "#007A3D", "secondary": "#CE1126", "formation": "4-4-2",
     "strengths": "Surprise element, passionate players, defensive organization",
     "weaknesses": "Significant quality gap to most opponents, first WC",
     "outlook": "Jordan's historic first World Cup is a massive achievement. They'll play hard and represent Asia with pride.",
     "qualification": "AFC playoff"},
    {"name": "Uzbekistan", "fifa_rank": 71, "elo": 1530, "form": 6.0, "confed": "AFC", "flag": "🇺🇿",
     "manager": "Srecko Katanec", "manager_nat": "Slovenian", "founded": 1946, "nickname": "White Wolves",
     "stadium": "Pakhtakor Stadium", "squad_value": 20, "wc_apps": 0, "best": "First appearance",
     "primary": "#1EB53A", "secondary": "#FFFFFF", "formation": "4-4-2",
     "strengths": "Improving Central Asian quality, no pressure, motivated to prove themselves",
     "weaknesses": "First World Cup, facing massive quality gap",
     "outlook": "Uzbekistan's debut. A momentous occasion for Central Asian football. Every minute at this tournament is historic for them.",
     "qualification": "AFC playoff"},
    # OFC
    {"name": "New Zealand", "fifa_rank": 97, "elo": 1470, "form": 5.5, "confed": "OFC", "flag": "🇳🇿",
     "manager": "Darren Bazeley", "manager_nat": "New Zealander", "founded": 1891, "nickname": "All Whites",
     "stadium": "Eden Park", "squad_value": 12, "wc_apps": 2, "best": "Group Stage",
     "primary": "#FFFFFF", "secondary": "#000000", "formation": "4-4-2",
     "strengths": "Organization, hard work, represent Oceania's best",
     "weaknesses": "Significant quality gap to virtually all opponents",
     "outlook": "New Zealand represent an entire confederation. Their presence adds global coverage. Every moment is history for Oceanian football.",
     "qualification": "OFC champions"},
]


# ─── REAL-SOUNDING PLAYERS ──────────────────────────────────────────────────────

PLAYER_TEMPLATES = {
    "Argentina": [
        ("Emiliano Martinez", "GK", 1, 31, 188, "Right", "Aston Villa", "England", 65, 0, 0, False, 93, True),
        ("Nahuel Molina", "RB", 26, 26, 181, "Right", "Atletico Madrid", "Spain", 28, 2, 6, False, 80, False),
        ("Cristian Romero", "CB", 13, 26, 185, "Right", "Tottenham Hotspur", "England", 45, 3, 0, False, 86, False),
        ("Nicolas Otamendi", "CB", 19, 36, 183, "Right", "Benfica", "Portugal", 102, 6, 0, False, 82, False),
        ("Nicolas Tagliafico", "LB", 3, 32, 172, "Left", "Lyon", "France", 72, 4, 9, False, 79, False),
        ("Rodrigo De Paul", "CM", 7, 30, 180, "Right", "Atletico Madrid", "Spain", 66, 8, 14, False, 85, False),
        ("Enzo Fernandez", "CM", 24, 23, 178, "Right", "Chelsea", "England", 38, 5, 10, False, 87, False),
        ("Alexis Mac Allister", "CM", 20, 25, 174, "Right", "Liverpool", "England", 40, 7, 8, False, 86, False),
        ("Lionel Messi", "RW", 10, 37, 170, "Left", "Inter Miami", "USA", 191, 109, 57, False, 93, True),
        ("Julian Alvarez", "ST", 9, 24, 170, "Right", "Atletico Madrid", "Spain", 45, 19, 12, False, 88, False),
        ("Lautaro Martinez", "CF", 22, 26, 174, "Right", "Inter Milan", "Italy", 62, 30, 8, False, 88, False),
    ],
    "Brazil": [
        ("Alisson Becker", "GK", 1, 31, 191, "Right", "Liverpool", "England", 83, 0, 0, False, 93, True),
        ("Danilo", "RB", 2, 32, 184, "Right", "Juventus", "Italy", 94, 9, 12, False, 83, False),
        ("Eder Militao", "CB", 3, 26, 186, "Right", "Real Madrid", "Spain", 42, 5, 1, False, 87, False),
        ("Marquinhos", "CB", 4, 29, 183, "Right", "PSG", "France", 97, 12, 5, False, 88, False),
        ("Wendell", "LB", 6, 30, 178, "Left", "Porto", "Portugal", 25, 1, 5, False, 77, False),
        ("Casemiro", "CDM", 5, 32, 185, "Right", "Manchester United", "England", 81, 10, 6, False, 88, True),
        ("Lucas Paqueta", "CAM", 10, 26, 180, "Right", "West Ham", "England", 60, 15, 18, False, 86, False),
        ("Rodrygo", "RW", 11, 23, 174, "Right", "Real Madrid", "Spain", 42, 14, 12, False, 87, False),
        ("Vinicius Junior", "LW", 20, 23, 176, "Right", "Real Madrid", "Spain", 56, 22, 14, False, 92, False),
        ("Raphinha", "RM", 18, 27, 176, "Right", "Barcelona", "Spain", 50, 23, 15, False, 86, False),
        ("Endrick", "ST", 9, 18, 173, "Right", "Real Madrid", "Spain", 12, 6, 2, False, 84, False),
    ],
    "France": [
        ("Mike Maignan", "GK", 16, 28, 191, "Right", "AC Milan", "Italy", 35, 0, 0, False, 90, False),
        ("Jules Kounde", "RB", 5, 25, 178, "Right", "Barcelona", "Spain", 42, 3, 5, False, 86, False),
        ("William Saliba", "CB", 17, 23, 192, "Right", "Arsenal", "England", 28, 2, 0, False, 87, False),
        ("Dayot Upamecano", "CB", 4, 25, 186, "Right", "Bayern Munich", "Germany", 38, 2, 0, False, 85, False),
        ("Theo Hernandez", "LB", 22, 26, 184, "Left", "AC Milan", "Italy", 41, 8, 12, False, 87, False),
        ("N'Golo Kante", "CDM", 13, 33, 169, "Right", "Al-Ittihad", "Saudi Arabia", 82, 4, 6, False, 86, False),
        ("Adrien Rabiot", "CM", 14, 29, 188, "Right", "Juventus", "Italy", 55, 9, 7, False, 83, False),
        ("Antoine Griezmann", "CAM", 7, 32, 176, "Right", "Atletico Madrid", "Spain", 125, 51, 35, False, 87, False),
        ("Ousmane Dembele", "RW", 11, 26, 178, "Right", "PSG", "France", 57, 10, 15, True, 85, False),
        ("Kylian Mbappe", "ST", 10, 25, 178, "Right", "Real Madrid", "Spain", 95, 54, 32, False, 97, True),
        ("Marcus Thuram", "CF", 9, 26, 187, "Right", "Inter Milan", "Italy", 38, 13, 8, False, 84, False),
    ],
    "England": [
        ("Jordan Pickford", "GK", 1, 30, 185, "Right", "Everton", "England", 69, 0, 0, False, 85, False),
        ("Trent Alexander-Arnold", "RB", 66, 25, 175, "Right", "Real Madrid", "Spain", 43, 5, 12, False, 88, False),
        ("John Stones", "CB", 5, 29, 188, "Right", "Manchester City", "England", 76, 3, 3, False, 85, False),
        ("Harry Maguire", "CB", 6, 31, 194, "Right", "Manchester United", "England", 64, 7, 1, False, 80, False),
        ("Luke Shaw", "LB", 3, 28, 182, "Left", "Manchester United", "England", 32, 1, 5, True, 82, False),
        ("Declan Rice", "CDM", 4, 25, 188, "Right", "Arsenal", "England", 53, 4, 6, False, 88, False),
        ("Jude Bellingham", "CAM", 22, 20, 186, "Right", "Real Madrid", "Spain", 39, 17, 12, False, 93, True),
        ("Phil Foden", "LW", 47, 24, 171, "Right", "Manchester City", "England", 47, 15, 18, False, 89, False),
        ("Bukayo Saka", "RW", 7, 22, 178, "Right", "Arsenal", "England", 49, 18, 16, False, 88, False),
        ("Harry Kane", "ST", 9, 30, 188, "Right", "Bayern Munich", "Germany", 97, 67, 22, False, 92, False),
        ("Cole Palmer", "AM", 20, 22, 185, "Right", "Chelsea", "England", 11, 4, 6, False, 84, False),
    ],
    "Spain": [
        ("Unai Simon", "GK", 1, 27, 190, "Left", "Athletic Club", "Spain", 42, 0, 0, False, 84, False),
        ("Dani Carvajal", "RB", 2, 32, 173, "Right", "Real Madrid", "Spain", 72, 3, 8, False, 85, False),
        ("Aymeric Laporte", "CB", 14, 30, 189, "Left", "Al-Nassr", "Saudi Arabia", 42, 6, 1, False, 84, False),
        ("Robin Le Normand", "CB", 23, 27, 188, "Right", "Atletico Madrid", "Spain", 18, 1, 0, False, 83, False),
        ("Alejandro Balde", "LB", 3, 20, 182, "Left", "Barcelona", "Spain", 21, 2, 5, False, 83, False),
        ("Rodri", "CDM", 16, 27, 191, "Right", "Manchester City", "England", 48, 4, 5, False, 93, True),
        ("Pedri", "CM", 26, 21, 174, "Right", "Barcelona", "Spain", 36, 6, 9, True, 88, False),
        ("Fabian Ruiz", "CM", 8, 27, 189, "Right", "PSG", "France", 39, 5, 7, False, 84, False),
        ("Lamine Yamal", "RW", 19, 17, 180, "Right", "Barcelona", "Spain", 22, 7, 11, False, 90, False),
        ("Alvaro Morata", "ST", 7, 31, 187, "Right", "AC Milan", "Italy", 73, 36, 18, False, 83, False),
        ("Nico Williams", "LW", 17, 22, 180, "Left", "Athletic Club", "Spain", 28, 9, 12, False, 86, False),
    ],
    "Germany": [
        ("Manuel Neuer", "GK", 1, 38, 193, "Right", "Bayern Munich", "Germany", 124, 0, 1, True, 88, False),
        ("Benjamin Pavard", "RB", 5, 28, 186, "Right", "Inter Milan", "Italy", 57, 5, 3, False, 84, False),
        ("Antonio Rudiger", "CB", 2, 31, 190, "Right", "Real Madrid", "Spain", 67, 4, 0, False, 86, False),
        ("Jonathan Tah", "CB", 4, 28, 195, "Right", "Bayer Leverkusen", "Germany", 23, 2, 0, False, 83, False),
        ("David Raum", "LB", 3, 26, 180, "Left", "RB Leipzig", "Germany", 26, 3, 8, False, 81, False),
        ("Robert Andrich", "CDM", 23, 29, 185, "Right", "Bayer Leverkusen", "Germany", 18, 2, 3, False, 81, False),
        ("Florian Wirtz", "CAM", 10, 21, 176, "Right", "Bayer Leverkusen", "Germany", 21, 7, 12, False, 89, False),
        ("Jamal Musiala", "AM", 14, 21, 183, "Right", "Bayern Munich", "Germany", 38, 12, 16, False, 91, True),
        ("Serge Gnabry", "RW", 7, 29, 176, "Right", "Bayern Munich", "Germany", 46, 22, 13, False, 84, False),
        ("Kai Havertz", "ST", 9, 25, 189, "Right", "Arsenal", "England", 55, 22, 12, False, 86, False),
        ("Leroy Sane", "LW", 19, 28, 183, "Right", "Bayern Munich", "Germany", 50, 18, 19, False, 85, False),
    ],
    "Portugal": [
        ("Diogo Costa", "GK", 1, 24, 188, "Right", "Porto", "Portugal", 28, 0, 0, False, 85, False),
        ("Joao Cancelo", "RB", 5, 29, 182, "Right", "Barcelona", "Spain", 65, 7, 15, False, 86, False),
        ("Ruben Dias", "CB", 6, 27, 187, "Right", "Manchester City", "England", 64, 6, 1, False, 90, True),
        ("Danilo Pereira", "CB", 3, 32, 187, "Right", "PSG", "France", 72, 9, 3, False, 82, False),
        ("Nuno Mendes", "LB", 22, 21, 180, "Left", "PSG", "France", 28, 2, 7, False, 85, False),
        ("Vitinha", "CM", 8, 24, 172, "Right", "PSG", "France", 38, 4, 8, False, 84, False),
        ("Bruno Fernandes", "CAM", 8, 29, 179, "Right", "Manchester United", "England", 78, 28, 21, False, 89, False),
        ("Bernardo Silva", "AM", 10, 29, 173, "Right", "Manchester City", "England", 80, 25, 28, False, 89, False),
        ("Pedro Neto", "LW", 7, 24, 172, "Left", "Chelsea", "England", 28, 4, 8, False, 84, False),
        ("Cristiano Ronaldo", "ST", 7, 39, 187, "Right", "Al-Nassr", "Saudi Arabia", 217, 130, 42, False, 88, False),
        ("Goncalo Ramos", "CF", 9, 23, 184, "Right", "PSG", "France", 22, 12, 3, False, 84, False),
    ],
    "Netherlands": [
        ("Bart Verbruggen", "GK", 1, 21, 194, "Right", "Brighton", "England", 12, 0, 0, False, 81, False),
        ("Denzel Dumfries", "RB", 22, 28, 188, "Right", "Inter Milan", "Italy", 56, 8, 14, False, 84, False),
        ("Stefan de Vrij", "CB", 6, 32, 189, "Right", "Inter Milan", "Italy", 60, 3, 2, False, 83, False),
        ("Virgil van Dijk", "CB", 4, 32, 193, "Right", "Liverpool", "England", 66, 7, 2, False, 89, True),
        ("Ian Maatsen", "LB", 3, 22, 175, "Left", "Borussia Dortmund", "Germany", 8, 1, 4, False, 80, False),
        ("Ryan Gravenberch", "CM", 8, 22, 190, "Right", "Liverpool", "England", 22, 2, 5, False, 83, False),
        ("Tijjani Reijnders", "CM", 14, 25, 183, "Right", "AC Milan", "Italy", 22, 5, 7, False, 84, False),
        ("Xavi Simons", "CAM", 21, 21, 176, "Right", "RB Leipzig", "Germany", 18, 4, 7, False, 84, False),
        ("Cody Gakpo", "LW", 11, 25, 189, "Left", "Liverpool", "England", 36, 16, 14, False, 86, False),
        ("Memphis Depay", "ST", 10, 30, 175, "Right", "Atletico Madrid", "Spain", 98, 45, 30, False, 83, False),
        ("Wout Weghorst", "CF", 9, 31, 197, "Right", "Hoffenheim", "Germany", 40, 8, 4, False, 79, False),
    ],
    "Belgium": [
        ("Thibaut Courtois", "GK", 1, 31, 199, "Right", "Real Madrid", "Spain", 101, 0, 0, False, 93, True),
        ("Timothy Castagne", "RB", 3, 28, 184, "Right", "Fulham", "England", 49, 4, 8, False, 80, False),
        ("Jan Vertonghen", "CB", 5, 36, 189, "Right", "RSC Anderlecht", "Belgium", 151, 9, 7, False, 79, False),
        ("Wout Faes", "CB", 24, 26, 190, "Right", "Leicester City", "England", 22, 3, 0, False, 80, False),
        ("Arthur Theate", "LB", 22, 23, 186, "Left", "Stade Rennais", "France", 20, 3, 2, False, 79, False),
        ("Youri Tielemans", "CM", 8, 27, 176, "Right", "Aston Villa", "England", 74, 12, 15, False, 83, False),
        ("Amadou Onana", "CM", 4, 22, 197, "Right", "Aston Villa", "England", 28, 2, 3, False, 83, False),
        ("Kevin De Bruyne", "CAM", 7, 33, 181, "Right", "Manchester City", "England", 106, 26, 47, True, 91, False),
        ("Leandro Trossard", "LW", 11, 29, 172, "Left", "Arsenal", "England", 44, 11, 14, False, 83, False),
        ("Romelu Lukaku", "ST", 9, 31, 191, "Right", "Roma", "Italy", 111, 77, 24, False, 85, False),
        ("Jeremy Doku", "RW", 19, 22, 167, "Left", "Manchester City", "England", 28, 6, 10, False, 84, False),
    ],
    "Croatia": [
        ("Dominik Livakovic", "GK", 1, 28, 188, "Right", "Fenerbahce", "Turkey", 47, 0, 0, False, 85, False),
        ("Josip Stanisic", "RB", 22, 24, 186, "Right", "Bayer Leverkusen", "Germany", 22, 2, 4, False, 79, False),
        ("Josip Sutalo", "CB", 6, 23, 190, "Right", "Ajax", "Netherlands", 15, 2, 0, False, 78, False),
        ("Duje Caleta-Car", "CB", 5, 28, 190, "Right", "Southampton", "England", 35, 2, 0, False, 79, False),
        ("Josip Juranovic", "LB", 3, 28, 179, "Right", "Union Berlin", "Germany", 42, 5, 6, False, 80, False),
        ("Luka Modric", "CM", 10, 38, 172, "Right", "Real Madrid", "Spain", 174, 24, 35, False, 88, True),
        ("Mateo Kovacic", "CM", 8, 29, 177, "Right", "Manchester City", "England", 99, 5, 18, False, 85, False),
        ("Mario Pasalic", "CM", 7, 29, 188, "Right", "Atalanta", "Italy", 62, 14, 15, False, 81, False),
        ("Ivan Perisic", "LW", 4, 35, 185, "Left", "Hajduk Split", "Croatia", 120, 34, 38, False, 80, False),
        ("Bruno Petkovic", "ST", 9, 30, 192, "Right", "Dinamo Zagreb", "Croatia", 44, 16, 6, False, 78, False),
        ("Andrej Kramaric", "CF", 9, 33, 177, "Right", "Hoffenheim", "Germany", 80, 35, 23, False, 82, False),
    ],
    "Morocco": [
        ("Yassine Bounou", "GK", 1, 33, 192, "Right", "Al-Hilal", "Saudi Arabia", 65, 0, 0, False, 88, True),
        ("Achraf Hakimi", "RB", 2, 25, 181, "Right", "PSG", "France", 72, 11, 20, False, 91, False),
        ("Romain Saiss", "CB", 5, 34, 191, "Right", "Beşiktaş", "Turkey", 75, 8, 2, False, 80, False),
        ("Nayef Aguerd", "CB", 4, 27, 188, "Right", "West Ham", "England", 42, 3, 0, False, 83, False),
        ("Noussair Mazraoui", "LB", 12, 26, 182, "Right", "Manchester United", "England", 48, 4, 8, False, 83, False),
        ("Sofyan Amrabat", "CDM", 4, 27, 181, "Right", "Fiorentina", "Italy", 55, 2, 3, False, 84, False),
        ("Azzedine Ounahi", "CM", 8, 23, 175, "Right", "Marseille", "France", 32, 3, 5, False, 82, False),
        ("Hakim Ziyech", "CAM", 7, 31, 174, "Right", "Galatasaray", "Turkey", 68, 22, 23, False, 83, False),
        ("Sofiane Boufal", "LW", 11, 30, 173, "Left", "Angers", "France", 58, 12, 14, False, 79, False),
        ("Youssef En-Nesyri", "ST", 9, 26, 192, "Right", "Fenerbahce", "Turkey", 54, 22, 7, False, 83, False),
        ("Ilias Chair", "AM", 10, 27, 174, "Right", "QPR", "England", 20, 4, 6, False, 78, False),
    ],
    "Japan": [
        ("Shuichi Gonda", "GK", 1, 34, 185, "Right", "Shimizu S-Pulse", "Japan", 65, 0, 0, False, 80, False),
        ("Hiroki Sakai", "RB", 5, 33, 180, "Right", "Urawa Red Diamonds", "Japan", 68, 5, 9, False, 79, False),
        ("Shogo Taniguchi", "CB", 3, 31, 183, "Right", "Kawasaki Frontale", "Japan", 32, 3, 0, False, 77, False),
        ("Ko Itakura", "CB", 4, 27, 187, "Right", "Borussia M'gladbach", "Germany", 30, 4, 0, False, 80, False),
        ("Yuto Nagatomo", "LB", 5, 37, 170, "Left", "FC Tokyo", "Japan", 145, 4, 10, False, 77, False),
        ("Wataru Endo", "CDM", 6, 30, 178, "Right", "Liverpool", "England", 46, 5, 3, False, 82, True),
        ("Hidemasa Morita", "CM", 10, 29, 176, "Right", "Sporting CP", "Portugal", 32, 5, 7, False, 81, False),
        ("Takefusa Kubo", "RW", 20, 22, 173, "Right", "Real Sociedad", "Spain", 32, 4, 8, False, 84, False),
        ("Kaoru Mitoma", "LW", 10, 26, 178, "Left", "Brighton", "England", 38, 10, 12, False, 87, False),
        ("Daichi Kamada", "CAM", 15, 27, 182, "Right", "Crystal Palace", "England", 38, 12, 10, False, 83, False),
        ("Ayase Ueda", "ST", 9, 25, 182, "Right", "Feyenoord", "Netherlands", 22, 9, 3, False, 80, False),
    ],
    "Senegal": [
        ("Edouard Mendy", "GK", 16, 32, 197, "Right", "Al-Ahli", "Saudi Arabia", 52, 0, 0, False, 85, True),
        ("Ismail Jakobs", "LB", 3, 24, 179, "Left", "Monaco", "France", 28, 2, 6, False, 79, False),
        ("Kalidou Koulibaly", "CB", 5, 32, 187, "Right", "Al-Hilal", "Saudi Arabia", 80, 10, 2, False, 86, False),
        ("Abdou Diallo", "CB", 19, 27, 187, "Right", "RB Leipzig", "Germany", 38, 4, 0, False, 80, False),
        ("Moussa Wague", "RB", 12, 27, 176, "Right", "Barcelona", "Spain", 18, 1, 3, False, 77, False),
        ("Nampalys Mendy", "CDM", 6, 31, 170, "Right", "Reims", "France", 30, 1, 2, False, 76, False),
        ("Idrissa Gueye", "CM", 15, 34, 174, "Right", "Everton", "England", 92, 4, 5, False, 80, False),
        ("Pape Matar Sarr", "CM", 29, 21, 182, "Right", "Tottenham", "England", 22, 3, 5, False, 82, False),
        ("Ismaila Sarr", "RW", 17, 26, 183, "Right", "Marseille", "France", 58, 16, 14, False, 83, False),
        ("Sadio Mane", "LW", 10, 32, 175, "Right", "Al-Nassr", "Saudi Arabia", 110, 45, 28, False, 86, False),
        ("Habib Diallo", "ST", 9, 29, 181, "Right", "Strasbourg", "France", 38, 15, 7, False, 79, False),
    ],
}


def get_mock_player(team_name: str, index: int, is_captain: bool = False):
    """Generate a realistic-sounding player for teams without templates."""
    positions = ["GK"] + ["CB"] * 2 + ["LB", "RB"] + ["CM"] * 2 + ["CDM"] + ["LW", "RW", "ST"]
    pos = positions[index % len(positions)]
    pos_codes = {"GK": "GK", "CB": "CB", "LB": "LB", "RB": "RB", "CDM": "CDM", "CM": "CM", "CAM": "CAM", "LW": "LW", "RW": "RW", "ST": "ST", "CF": "CF", "AM": "CAM"}

    first_names = ["Carlos", "Ahmed", "Miguel", "David", "Marco", "Luis", "Juan", "Ali", "Omar", "Yusuf",
                   "Stefan", "Ivan", "Andrei", "Tomas", "Radu", "Dmitri", "Hassan", "Kwame", "Diallo", "Yaya"]
    last_names = ["Santos", "Hernandez", "Rodriguez", "Garcia", "Lopez", "Martinez", "Gonzalez", "Perez",
                  "Ibrahim", "Mohammed", "Mueller", "Schmidt", "Fischer", "Wagner", "Becker", "Weber",
                  "Diallo", "Traore", "Mensah", "Osei", "Park", "Kim", "Lee", "Choi"]

    name = f"{random.choice(first_names)} {random.choice(last_names)}"
    return {
        "name": name, "position": pos, "position_code": pos_codes.get(pos, pos),
        "jersey_number": index + 1, "age": random.randint(21, 34),
        "height_cm": random.randint(172, 196), "preferred_foot": random.choice(["Right", "Left"]),
        "club": f"Club {random.choice(['FC', 'United', 'City', 'Athletic'])} {random.randint(1, 20)}",
        "national_appearances": random.randint(5, 80),
        "market_value": round(random.uniform(2.0, 60.0), 1),
        "recent_form": round(random.uniform(5.5, 9.0), 1),
        "goals": random.randint(0, 20) if pos != "GK" else 0,
        "assists": random.randint(0, 15) if pos not in ["GK", "CB", "LB", "RB"] else 0,
        "injury_status": random.random() < 0.1,
        "ai_rating": random.randint(74, 86),
        "is_captain": is_captain,
    }


def seed_wc_history(team, history_list):
    for h in history_list:
        HistoricalWorldCup.objects.get_or_create(team=team, year=h[0], defaults={
            "host_nation": h[1], "stage_reached": h[2], "final_placement": h[3],
            "goals_scored": h[4], "goals_conceded": h[5], "matches_played": h[6],
        })


WC_HISTORY = {
    "Brazil": [
        (2022, "Qatar", "Quarterfinals", 8, 8, 5, 5), (2018, "Russia", "Quarterfinals", 8, 6, 4, 5),
        (2014, "Brazil", "4th Place", 4, 14, 9, 7), (2010, "South Africa", "Quarterfinals", 8, 5, 3, 5),
        (2006, "Germany", "Quarterfinals", 8, 7, 2, 5), (2002, "South Korea/Japan", "Champions", 1, 18, 4, 7),
        (1998, "France", "Runners-up", 2, 14, 10, 7), (1994, "USA", "Champions", 1, 11, 3, 7),
    ],
    "France": [
        (2022, "Qatar", "Runners-up", 2, 16, 8, 7), (2018, "Russia", "Champions", 1, 12, 6, 7),
        (2014, "Brazil", "Quarterfinals", 8, 10, 3, 5), (2010, "South Africa", "Group Stage", None, 1, 4, 3),
        (2006, "Germany", "Runners-up", 2, 9, 3, 7), (2002, "South Korea/Japan", "Group Stage", None, 0, 3, 3),
        (1998, "France", "Champions", 1, 15, 2, 7), (1994, "USA", "N/A - did not qualify", None, 0, 0, 0),
    ],
    "Germany": [
        (2022, "Qatar", "Group Stage", None, 6, 6, 3), (2018, "Russia", "Group Stage", None, 5, 5, 3),
        (2014, "Brazil", "Champions", 1, 18, 4, 7), (2010, "South Africa", "3rd Place", 3, 16, 5, 7),
        (2006, "Germany", "3rd Place", 3, 14, 6, 7), (2002, "South Korea/Japan", "Runners-up", 2, 14, 7, 7),
        (1998, "France", "Quarterfinals", 8, 7, 3, 5), (1990, "Italy", "Champions", 1, 15, 5, 7),
    ],
    "Argentina": [
        (2022, "Qatar", "Champions", 1, 15, 8, 7), (2018, "Russia", "Round of 16", None, 6, 5, 4),
        (2014, "Brazil", "Runners-up", 2, 8, 4, 7), (2010, "South Africa", "Quarterfinals", 8, 10, 6, 5),
        (2006, "Germany", "Quarterfinals", 8, 11, 4, 5), (2002, "South Korea/Japan", "Group Stage", None, 2, 2, 3),
        (1998, "France", "Quarterfinals", 8, 10, 5, 5), (1986, "Mexico", "Champions", 1, 14, 5, 7),
    ],
    "Spain": [
        (2022, "Qatar", "Round of 16", None, 9, 7, 4), (2018, "Russia", "Round of 16", None, 6, 6, 4),
        (2014, "Brazil", "Group Stage", None, 4, 7, 3), (2010, "South Africa", "Champions", 1, 8, 2, 7),
        (2006, "Germany", "Round of 16", None, 6, 2, 4), (2002, "South Korea/Japan", "Quarterfinals", 8, 9, 6, 5),
    ],
    "England": [
        (2022, "Qatar", "Quarterfinals", 8, 12, 4, 5), (2018, "Russia", "4th Place", 4, 12, 8, 7),
        (2014, "Brazil", "Group Stage", None, 2, 6, 3), (2010, "South Africa", "Round of 16", None, 5, 4, 4),
        (2006, "Germany", "Quarterfinals", 8, 6, 2, 5), (2002, "South Korea/Japan", "Quarterfinals", 8, 6, 3, 5),
        (1998, "France", "Round of 16", None, 7, 6, 4), (1966, "England", "Champions", 1, 11, 3, 6),
    ],
    "Portugal": [
        (2022, "Qatar", "Quarterfinals", 8, 12, 5, 5), (2018, "Russia", "Round of 16", None, 7, 5, 4),
        (2014, "Brazil", "Group Stage", None, 4, 7, 3), (2010, "South Africa", "Round of 16", None, 8, 5, 4),
        (2006, "Germany", "4th Place", 4, 15, 9, 7), (2002, "South Korea/Japan", "Group Stage", None, 6, 4, 3),
    ],
    "Netherlands": [
        (2022, "Qatar", "Quarterfinals", 8, 8, 5, 5), (2018, "Russia", "N/A - did not qualify", None, 0, 0, 0),
        (2014, "Brazil", "3rd Place", 3, 15, 4, 7), (2010, "South Africa", "Runners-up", 2, 12, 6, 7),
        (2006, "Germany", "Round of 16", None, 9, 3, 4), (1978, "Argentina", "Runners-up", 2, 9, 4, 6),
        (1974, "West Germany", "Runners-up", 2, 15, 4, 7),
    ],
    "Morocco": [
        (2022, "Qatar", "4th Place", 4, 6, 5, 7), (2018, "Russia", "Group Stage", None, 2, 4, 3),
        (2014, "Brazil", "Group Stage", None, 2, 6, 3),
    ],
    "Japan": [
        (2022, "Qatar", "Round of 16", None, 4, 3, 4), (2018, "Russia", "Round of 16", None, 6, 6, 4),
        (2014, "Brazil", "Group Stage", None, 2, 6, 3),
    ],
}


def run():
    print("Clearing all existing data...")
    HistoricalWorldCup.objects.all().delete()
    FanSupport.objects.all().delete()
    Player.objects.all().delete()
    Team.objects.all().delete()
    print("Done. Seeding 48 teams...")

    # Remove duplicate Japan entry
    seen_names = set()
    unique_teams = []
    for t in TEAMS:
        if t["name"] not in seen_names:
            unique_teams.append(t)
            seen_names.add(t["name"])

    team_objs = {}
    for i, t in enumerate(unique_teams):
        team = Team.objects.create(
            name=t["name"], fifa_rank=i + 1,
            elo_rating=t["elo"], recent_form=t["form"],
            confederation=t["confed"], flag_emoji=t["flag"],
            manager_name=t.get("manager", ""), manager_nationality=t.get("manager_nat", ""),
            foundation_year=t.get("founded", 1900), nickname=t.get("nickname", ""),
            home_stadium=t.get("stadium", ""), squad_market_value=t.get("squad_value", 100),
            world_cup_appearances=t.get("wc_apps", 0), best_wc_result=t.get("best", ""),
            primary_color=t.get("primary", "#FFFFFF"), secondary_color=t.get("secondary", "#000000"),
            tactical_formation=t.get("formation", "4-3-3"),
            strengths=t.get("strengths", ""), weaknesses=t.get("weaknesses", ""),
            historical_performance=t.get("best", ""), ai_outlook=t.get("outlook", ""),
            qualification_path=t.get("qualification", ""),
            fan_support_count=random.randint(0, 50000),
        )
        team_objs[t["name"]] = team
        print(f"  ✓ {team.name}")

    print("\nSeeding players...")
    for team_name, team in team_objs.items():
        captain_set = False
        if team_name in PLAYER_TEMPLATES:
            for p in PLAYER_TEMPLATES[team_name]:
                is_cap = p[12]
                Player.objects.create(
                    name=p[0], team=team, position=p[1],
                    position_code=p[1] if p[1] in ["GK", "CB", "LB", "RB", "CDM", "CM", "CAM", "LW", "RW", "ST"] else "CM",
                    jersey_number=p[2], age=p[3], height_cm=p[4],
                    preferred_foot=p[5], club=p[6], club_country=p[7],
                    national_appearances=p[8], goals=p[9], assists=p[10],
                    injury_status=p[11], ai_rating=p[12],
                    is_captain=p[13] if len(p) > 13 else False,
                    market_value=round(random.uniform(5.0, 200.0), 1),
                    recent_form=round(random.uniform(7.0, 9.8), 1),
                    minutes_played=random.randint(200, 900),
                )
        else:
            for idx in range(11):
                is_cap = idx == 9 and not captain_set
                if is_cap:
                    captain_set = True
                pdata = get_mock_player(team_name, idx, is_cap)
                Player.objects.create(
                    name=pdata["name"], team=team, position=pdata["position"],
                    position_code=pdata["position_code"], jersey_number=pdata["jersey_number"],
                    age=pdata["age"], height_cm=pdata["height_cm"],
                    preferred_foot=pdata["preferred_foot"], club=pdata["club"],
                    national_appearances=pdata["national_appearances"],
                    market_value=pdata["market_value"], recent_form=pdata["recent_form"],
                    goals=pdata["goals"], assists=pdata["assists"],
                    injury_status=pdata["injury_status"], ai_rating=pdata["ai_rating"],
                    is_captain=pdata["is_captain"], minutes_played=random.randint(100, 900),
                )
        print(f"  ✓ {team.name} players seeded")

    print("\nSeeding World Cup history...")
    for team_name, history in WC_HISTORY.items():
        if team_name in team_objs:
            seed_wc_history(team_objs[team_name], history)
            print(f"  ✓ {team_name} WC history")

    print("\nCreating fan support records...")
    for team in Team.objects.all():
        FanSupport.objects.create(
            team=team,
            total_supporters=team.fan_support_count,
            supporters_today=random.randint(0, 5000),
            supporters_this_week=random.randint(0, 20000),
        )

    print(f"\n✅ V3 Seed complete! {Team.objects.count()} teams, {Player.objects.count()} players seeded.")


if __name__ == "__main__":
    run()
